spring:
  profiles:
    active: local
---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/bulpan?characterEncoding=UTF-8&serverTimezone=UTC
    username: ejjoo